### ISSUE TITLE
huggingface_hub

### ISSUE THREAD

**Issue by MachineCase** [mrphrazer/reverser_ai#2]
Hi,

I tried to resolve the path for huggingface_hub, but it didn't work. It's installed, but it's not able to find the module. Any tips on how to fix it or something else that might be the issue?

<img width="1035" alt="Screenshot 2024-03-19 at 17 48 17" src="https://github.com/mrphrazer/reverser_ai/assets/89738954/e5c670e8-73ba-49ec-baab-680a622611c6">

**Comment by mrphrazer** [comment]
Hi! I tested it before on another system, but it seems there seems to be a depency missing.Can you try

```
pip3 install huggingface-hub
```

where pip3 should be the same Python version (3.10/3.11/3.12) as configured as your Python interpreter used by BinaryNinja

**Comment by mrphrazer** [comment]
Update: On MacOS, its important that pip and python version match. For instance, if I've set the Python interpreter:

<img width="1015" alt="image" src="https://github.com/mrphrazer/reverser_ai/assets/10834372/404fa36b-7896-4691-b7fe-1209c73b3304">

Then I've to install it with `pip3.11 install ...`. The packages won't be shared, e.g., with `pip3.12` / `python3.12`.

**Comment by psifertex** [comment]
Note that there's an action in BN: `install python3 module...` that you can use to install pip dependencies for the currently selected interpreter.

**Comment by mrphrazer** [comment]
I'll close this for now since it just seems to be a version mismatch between Binja's interpreter and the locally installed one. Feel free to open it again if you've any further issues
