### ISSUE TITLE
No module named Typer

### ISSUE THREAD

**Issue by thrypuro** [mrphrazer/reverser_ai#3]
Go the error in the title, i had to pip3 install this separately.  Maybe it's worth adding it to the requirements.txt?

**Comment by mrphrazer** [comment]
Hi, thanks! On which system (Windows/Linux/MacOS) caused this a problem and how did you install the plugin (command line interface vs. Plugin Manager)? I've checked on my Linux/MacOS systems and don't have it anywhere installed and works fine; I'm also not sure which library requires that, its not ReverserAI itself

**Comment by thrypuro** [comment]
I am on Linux, specifically Fedora 39 in particular, which requires it installed for some reason. 
I just `pip3 install typer` separately, on a terminal (so cli, not the plugin manager itself) and it works perfectly. Perhaps it's hugging face or some other module that requires it.

**Comment by mrphrazer** [comment]
okay, strange. I've pushed a fix onto another branch and will incorporate it in the next release: https://github.com/mrphrazer/reverser_ai/commit/845626f9548d519ab128a66c198e56370592d68a

Thanks!
