### ISSUE TITLE
An error occurs during installation

### ISSUE THREAD

**Issue by contt123** [mrphrazer/reverser_ai#4]
All packages are installed. However, a text like the picture appears and installation does not work.
![2024-03-25 16 58 56](https://github.com/mrphrazer/reverser_ai/assets/75321958/6ba31f68-d49f-455c-92a4-cde3dc476e5d)

**Comment by mrphrazer** [comment]
Hi,

did you check that your BinaryNinja version uses the same Python interpreter and runtime as your local system? Compare https://github.com/mrphrazer/reverser_ai/issues/2

**Comment by contt123** [comment]
![2024-03-26 10 54 26](https://github.com/mrphrazer/reverser_ai/assets/75321958/6e6bcac7-d2d8-4029-be04-f3d6f92e82f2)

The versions are the same. Still, the same problem occurs. help

binary ninja version is 3.5.4526

**Comment by mrphrazer** [comment]
Can you checkout the repo manually and try installing the dependencies like that:

```bash
# move to binary ninjas plugin folder
cd <...>/plugins

# clode repository
git clone https://github.com/mrphrazer/reverser_ai.git
cd reverser_ai

# install requirements
pip3 install -r requirements.txt

# install ReverserAI
pip3 install .
```

**Comment by contt123** [comment]
After reinstalling Binary Ninja, installation was completed normally.

**Comment by mrphrazer** [comment]
alright, thanks. I'll close it for nor. Feel free to reopen if you have similar problems in future
